server:
  port: 9527
spring:
  application:
    name: zuul-gateway
zuul:
  ignored-services: "*"
  prefix: "/services" #前缀
  routes: #路由的配置
      user.serviceId: yonghe-plat
      user.path: /user/**
      

